import type { Client, HoursEntry, InvoiceReport, WorkLog } from "@/types/domain";
import { exactElapsedMinutes, roundCurrency } from "@/lib/reports/engine";
export interface InvoiceDashboardSummary { byStatus: Record<InvoiceReport["status"], number>; revenueThisMonth: number; revenueYtd: number; outstandingInvoices: number; outstandingBalance: number; averagePaymentTimeDays: number | null; totalBillableHours: number; }
export interface ClientBillingHistory { clientId: string; clientName: string; invoices: InvoiceReport[]; hoursBilled: number; workLogs: WorkLog[]; totalRevenue: number; averageHourlyRate: number; outstandingBalance: number; lastInvoiceDate: string | null; }
export function summarizeInvoiceDashboard(invoices: readonly InvoiceReport[], hours: readonly HoursEntry[], today = new Date().toISOString().slice(0, 10)): InvoiceDashboardSummary {
  const month = today.slice(0, 7); const year = today.slice(0, 4); const paid = invoices.filter((i) => i.status === "paid"); const days = paid.map((i) => i.sentDate && i.paidDate ? (Date.parse(i.paidDate) - Date.parse(i.sentDate)) / 86400000 : null).filter((v): v is number => v !== null && v >= 0); const paidOn = (i: InvoiceReport) => i.paidDate ?? i.invoiceDate ?? i.periodEnd;
  return { byStatus: { draft: invoices.filter(i=>i.status==="draft").length, sent: invoices.filter(i=>i.status==="sent").length, paid: paid.length, void: invoices.filter(i=>i.status==="void").length }, revenueThisMonth: roundCurrency(paid.filter(i=>paidOn(i).slice(0,7)===month).reduce((s,i)=>s+i.totalAmount,0)), revenueYtd: roundCurrency(paid.filter(i=>paidOn(i).slice(0,4)===year).reduce((s,i)=>s+i.totalAmount,0)), outstandingInvoices: invoices.filter(i=>i.status==="sent" || i.status==="draft").length, outstandingBalance: roundCurrency(invoices.filter(i=>i.status==="sent" || i.status==="draft").reduce((s,i)=>s+i.totalAmount,0)), averagePaymentTimeDays: days.length ? Math.round((days.reduce((s,d)=>s+d,0)/days.length)*10)/10 : null, totalBillableHours: Math.round(hours.filter(h=>h.billable).reduce((s,h)=>s+exactElapsedMinutes(h.startTime,h.endTime,h.breakMinutes)/60,0)*100)/100 };
}
export function buildClientBillingHistory(clients: readonly Client[], invoices: readonly InvoiceReport[], hours: readonly HoursEntry[], workLogs: readonly WorkLog[]): ClientBillingHistory[] {
  return clients.map((client) => { const ci = invoices.filter(i=>i.clientId===client.id); const ch=hours.filter(h=>h.clientId===client.id && h.billable); const minutes=ch.reduce((s,h)=>s+exactElapsedMinutes(h.startTime,h.endTime,h.breakMinutes),0); const billed=ch.reduce((s,h)=>s+(exactElapsedMinutes(h.startTime,h.endTime,h.breakMinutes)/60)*h.hourlyRate,0); return { clientId: client.id, clientName: client.name, invoices: ci.sort((a,b)=>b.periodEnd.localeCompare(a.periodEnd)), hoursBilled: Math.round((minutes/60)*100)/100, workLogs: workLogs.filter(w=>w.clientId===client.id), totalRevenue: roundCurrency(ci.filter(i=>i.status==="paid").reduce((s,i)=>s+i.totalAmount,0)), averageHourlyRate: minutes ? roundCurrency(billed/(minutes/60)) : 0, outstandingBalance: roundCurrency(ci.filter(i=>i.status==="sent"||i.status==="draft").reduce((s,i)=>s+i.totalAmount,0)), lastInvoiceDate: ci.map(i=>i.invoiceDate ?? i.periodEnd).sort().at(-1) ?? null }; });
}
